name: Cypress Build and Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Choose the appropriate runner

    steps:
      - name: Clone Repository and Run Cypress Tests
        run: |
          git clone https://github.com/AhadMKhan/ahsan_cip.git cypress-project
          cd cypress-project
          npm install
          npx cypress run
